### PR TITLE
Fix OSH parsing under pandas 3.0; support Python 3.10–3.14 (drop 3.9)

### PR DESCRIPTION
**Pull request by HTenkanen**
## Summary

Fixes OSH (OpenStreetMap history `.osh.pbf`) timestamp parsing under **pandas 3.0**, and gets pyrosm building, testing, and installing cleanly across **Python 3.10–3.14**. Python 3.9 (end-of-life) is dropped.

## Problem

On Python 3.11+ the dependency stack resolves to **pandas 3.0**, where the string dtype is the default (PDEP-14): missing OSM tag values now surface as `pd.NA`, never Python `None`. The OSH way-record cleaner stripped empty tags with an identity check `y != None`, which no longer matches `pd.NA`. Every way record then retained the union of all tag keys (NA-valued); downstream the `highway` filter and tags-as-columns expansion admitted extra ways and columns, inflating `get_network(timestamp=...)` from `(210, 25)` to `(383, 27)` and breaking the buildings/graph OSH paths. The regression is pandas-version-driven (pandas 2.3.3 passes; 3.0.3 fails), not Python-version-driven.

In addition, the documented conda environments could not be created under modern conda/mamba (a malformed `cykhash=>2` spec), and the CI `lint` job failed in its `ubuntu:22.04` container with `GLIBC_2.38 not found`.

## Changes

**Bug fix (pandas 3.0)**
- `pyrosm/data_filter.pyx` — `clean_empty_values_from_ways` now drops `None`/`NaN`/`pd.NA` via a null-aware helper, while always keeping real values (incl. `0`/`""`) and array cells (the `nodes` key). Reproduces the pandas-2.x result exactly and fixes pandas 3.0.
- `pyrosm/utils/__init__.py` — replace deprecated `Timestamp.utcfromtimestamp` with `fromtimestamp(..., tz="UTC")` (same tz-aware UTC value; clears the `Pandas4Warning`).
- `tests/test_network_parsing.py` — regression test asserting no empty/NA tag column leaks into OSH network output and the shape stays `(210, 25)`.

**Python 3.10–3.14 support**
- `ci/313-conda.yaml`, `ci/314-conda.yaml` — new environments; added to the CI test matrix.
- `ci/311-conda.yaml`, `ci/312-conda.yaml` — fix malformed `cykhash=>2` → `cykhash>=2` so the documented environments resolve.
- Removed `ci/39-conda.yaml` and dropped Python 3.9 from the matrix (EOL Oct 2025).
- `setup.py` — `python_requires>=3.10`; classifiers updated to 3.10–3.14.
- `README.md` — dev setup section updated to 3.10–3.14.
- `tests/test_graph_exports.py` — the two `pandana` graph-export tests now `pytest.importorskip("pandana")`. pandana has no Python 3.13+ build on conda-forge, so it is omitted from the 3.13/3.14 envs and those tests skip there; they still run on 3.10–3.12.

**CI / housekeeping**
- `.github/workflows/tests.yaml` — build with `pip install -e . --no-build-isolation` so it uses the conda-provided build deps (Cython, cykhash, pyrobuf). Plain `pip install -e .` rebuilds pyrobuf from PyPI under build isolation, which fails against modern setuptools (`'PyrobufDistribution' object has no attribute 'dry_run'`). README dev instructions updated to match.
- `.github/workflows/tests.yaml` — drop the broken `ubuntu:22.04` lint container (fixes the `GLIBC_2.38` failure); bump `actions/checkout@v4` and `actions/setup-python@v5` (clears Node 20 deprecation).
- `.github/workflows/tests.yaml` — fix Codecov: pass the `CODECOV_TOKEN` secret (the old step never did, so uploads were tokenless and hit a 429 rate limit), bump `codecov-action@v3.1.1 → v5`, and set `fail_ci_if_error: false` so coverage upload can't gate the test suite.
- `.gitignore` — ignore `docs/maintenance` (local maintenance notes/plans).

## Validation

Built from source and ran the full test suite locally on every supported version:

| Python | pandas | result |
|--------|--------|--------|
| 3.10 | 2.3.3 | 107 passed, 2 skipped |
| 3.11 | 3.0.3 | 107 passed, 2 skipped |
| 3.12 | 3.0.3 | 107 passed, 2 skipped |
| 3.13 | 3.0.3 | 105 passed, 4 skipped (pandana) |
| 3.14 | 3.0.3 | 105 passed, 4 skipped (pandana) |

`black --check pyrosm` and `flake8 pyrosm` are clean.

## Notes

- **pandana** is unmaintained. Its graph-export tests are skipped where it cannot run: on Python 3.13/3.14 (no conda-forge build) and on Windows (its compiled `cyaccess` uses C `long` buffers, which are 32-bit on Windows and reject NumPy 2's int64 arrays). The export still works on Linux/macOS for 3.10–3.12. Migrating this export to the maintained successor [`pandarm`](https://github.com/oturns/pandarm) is intended as a separate PR.

### CODE REVIEW

**Review by HTenkanen — COMMENTED** [review]
All good
